### PR TITLE
connman_curses doesn't make clear which wireless interface is using when two or more wireless interfaces are available

### PR DESCRIPTION
**Pull request by alan-mushi**
Hello,

Recently I've started using `connman_curses` with two wireless interfaces simultaneously and I've found some confusing behaviors (they may be only confusing to me). I'll open a ticket per issue and you'll see if it's a real problem or not =). The first one is, when two or more wireless interfaces are available (it may be applicable to other technologies) `connman_curses` doesn't make clear which interface is using.

**Testcase**
1. Make available two or more wireless interfaces to the system
2. Disconnect from all wireless networks
3. Launch `connman_curses`
4. Select the `wifi technology`
   - `connman_curses` shows repeated some APs and doesn't specify which interface detects which AP and therefore I have no way to select conscientiously which interface connects to a specific AP.

0yk8cein

In the above image some AP essids are repeated, eg. **INFINITUMl8p4** , not all of them are repeated because one of the wireless interfaces is more sensitive than the other.

**Expected behavior**

I think `connman_curses` should state which wireless interface is detecting which AP or should list only once every AP detected if no specification is displayed, in that case it should use the interface with better range detection by default.

### CODE REVIEW

**Comment by javier-lopez** [comment]
Now it's aligned quite fine =). Thanks!

lifs1mwo

**Comment by alan-mushi** [comment]
@jobol Is there a problem with this PR ? If it's about the length of the "security" field I might be able to glean some characters here and there but in the end the minimal screen resolution is fairly small.

**Pull request merged**
